@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CodeConnectParser" as CodeConnectParser LOGIC_COLOR
participant ":FindCommandParser" as FindCommandParser LOGIC_COLOR
participant "f:FindCommand" as FindCommand LOGIC_COLOR
end box

[-> LogicManager : execute("find John")
activate LogicManager

LogicManager -> CodeConnectParser : parseCommand("find John")
activate CodeConnectParser

create FindCommandParser
CodeConnectParser -> FindCommandParser
activate FindCommandParser

FindCommandParser --> CodeConnectParser
deactivate FindCommandParser

CodeConnectParser -> FindCommandParser : parse("John")
activate FindCommandParser

create FindCommand
FindCommandParser -> FindCommand
activate FindCommand

FindCommand --> FindCommandParser :
deactivate FindCommand

FindCommandParser --> CodeConnectParser : f
deactivate FindCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindCommandParser -[hidden]-> CodeConnectParser
destroy FindCommandParser

CodeConnectParser --> LogicManager : f
deactivate CodeConnectParser

LogicManager -> FindCommand : execute(m:Model)
activate FindCommand

FindCommand -> FindCommand: Find contacts that contain John

FindCommand --> LogicManager : r
deactivate FindCommand

[<--LogicManager
deactivate LogicManager
@enduml
