@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam participant {
    TextColor black
}

box UI UI_COLOR_T1
    participant "ContactListView" as ContactListView UI_COLOR
end box

box Logic LOGIC_COLOR_T1
    participant "MailApp" as MailApp LOGIC_COLOR
    participant "Mail Application" as MailApplication LOGIC_COLOR
end box

actor User
[-> ContactListView : Clicks on email address
activate ContactListView
ContactListView -> MailApp : handleEmailClicked()
activate MailApp
MailApp -> MailApplication : openDefaultMailApp(email)
activate MailApplication
MailApplication --> User : Mail application opens with selected email
deactivate MailApplication
deactivate MailApp
deactivate ContactListView
@enduml