@startuml ContactClassDiagram
    class Team {
    }

    class Name
    class UniqueContactList
    class Contact
    class TeamStats

    Team *-- Name
    Team *--> "1" UniqueContactList
    Team *-- TeamStats
    UniqueContactList --> "*" Contact

@enduml
